spring:
  # PostgreSQL Configuration (for User entity)
  datasource:
    url: jdbc:postgresql://localhost:5432/endora
    username: oudom
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # MongoDB Configuration (for dynamic tables)
  data:
    mongodb:
      host: localhost
      port: 27017
      database: endora
      # username: your_mongo_username  # uncomment if auth enabled
      # password: your_mongo_password  # uncomment if auth enabled

  # Keycloak Configuration
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: https://endora-oauth2.istad.co/realms/endora_api

  # Virtual Threads
  threads:
    virtual:
      enabled: true

keycloak:
  server-url: https://endora-oauth2.istad.co/
  realm: endora_api
  admin:
    client-id: admin-cli
    client-secret: b2L6hrMg76JLk4GSLd8CGMPRJNnAOko2

server:
  port: 8080

# Make MongoDB connection optional
management:
  health:
    mongo:
      enabled: false

# Logging
logging:
  level:
    com.tochratana.api: DEBUG
    org.keycloak: DEBUG
